version: "3"
services:
  admin:
    image: vav87/admin-server:1.0
    ports:
      - 9003:9003

  client:
    image: vav87/client-service:1.0
    depends_on:
      - admin
    ports:
      - 8080:8080

  mongo:
    image: mongo
    restart: always
    volumes:
      - mongodb:/var/lib/mongodb

  mongoexpress:
    image: mongo-express
    restart: always
    depends_on:
      - mongo
    ports:
      - 8081:8081

volumes:
  mongodb: