version: "3"
services:
  mongo:
    image: mongo
    restart: always
    env_file:
      - .env
    volumes:
      - mongodb:/data/db

  mongoexpress:
    image: mongo-express
    restart: always
    env_file:
      - .env
    depends_on:
      - mongo
    ports:
      - 8081:8081

  adminserver:
    image: vav87/admin-server:1.0
    restart: on-failure
    ports:
      - 9003:9003

  client:
    image: vav87/client-service:1.0
    restart: on-failure
    env_file:
      - .env
    depends_on:
      - mongo
    ports:
      - 8080:8080

volumes:
  mongodb: